root = "."

tmp_dir = "tmp"

include_ext = ["go"]

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "GO_ENV=development ./tmp/main"

exclude_dir = ["frontend", "tmp", "bin", "pkg"]

exclude_regex = [
  "^pkg/mod/",
  "@v[0-9]",
  "testdata",
  ".*_test\\.go$"
]

[log]
main_only = true
color = true
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
