root = "."

tmp_dir = "tmp"

include_ext = ["go"]

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "tmp/main"
full_bin = "GO_ENV=development ./tmp/main"

exclude_dir = ["frontend", "tmp", "bin", "pkg"]

[log]
main_only = true
color = true
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
